version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    working_dir: /app
    volumes:
      - ./app:/app
    command: ["python", "main.py"]
    ports:
      - "5000:5000"
    restart: always
